[package]
name = "astrobox-ng-plugin-template-rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.47.0", features = ["async", "async-spawn"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
waki = "0.5.1"
serde_json = "1.0"
serde = "1.0"
